#eureka:
#  instance:
#    hostname: ${EUREKA_HOST_NAME}
#    appname: ${spring.application.name}
#  client:
#    fetchRegistry: ${BOOL_FETCH:false}
#    register-with-eureka: ${BOOL_REGISTER:false}
#    service-url:
#      default-Zone: ${EUREKA_URL_LIST:http://localhost:8761/eureka/}
#  server:
#    enable-self-preservation: ${SELF_PRESERVATION:true}

eureka:
  server:
    # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: ${SELF_PRESERVATION:true}
    use-read-only-response-cache: false
  client:
    # eureka client间隔多久去拉取服务注册信息 默认30s
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:${server.port}/eureka/}
    fetchRegistry: ${BOOL_FETCH:true}
    register-with-eureka: ${BOOL_REGISTER:true}
  instance:
    # 心跳间隔时间，即发送一次心跳之后，多久在发起下一次（缺省为30s）
    lease-renewal-interval-in-seconds: 5
    # 在收到一次心跳之后，等待下一次心跳的空档时间，大于心跳间隔即可，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 10
    #instance-id: ${EUREKA_INSTANCE_HOSTNAME:${spring.application.name}}:${server.port}@${random.long(1000000,9999999)}
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    appname: ${spring.application.name}

spring:
  application:
    name: ${EUREKA_APPLICATION_NAME}
server:
  port: 8761



